AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SrcBucket:
    Type: String
    Default: eecs6895-fraud-detection-repo

  ProjectName:
    Type: String
    Default: fraud-detection

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-lambda-service-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  ApprovalRequest:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-approval-request
      Runtime: python3.8
      Code:
        S3Bucket: !Ref SrcBucket
        S3Key: src/approvalRequest/code.zip
      Role: !GetAtt LambdaRole.Arn
      Handler: handler.handler

  BatchWriter:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-batch-writer
      Runtime: python3.8
      Code:
        S3Bucket: !Ref SrcBucket
        S3Key: src/batchWriter/code.zip
      Role: !GetAtt LambdaRole.Arn
      Handler: handler.handler

  CheckResult:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-check-result
      Runtime: python3.8
      Code:
        S3Bucket: !Ref SrcBucket
        S3Key: src/checkResult/code.zip
      Role: !GetAtt LambdaRole.Arn
      Handler: handler.handler

  Classifier:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-classifier
      Runtime: python3.8
      Code:
        S3Bucket: !Ref SrcBucket
        S3Key: src/classifier/code.zip
      Role: !GetAtt LambdaRole.Arn
      Handler: handler.handler

  VerifyTransaction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-verify-transaction
      Runtime: python3.8
      Code:
        S3Bucket: !Ref SrcBucket
        S3Key: src/verifyTransaction/code.zip
      Role: !GetAtt LambdaRole.Arn
      Handler: handler.handler