# nested stack - root
AWSTemplateFormatVersion: "2010-09-09"
Description: Fraud detection pipeline cloudformation code
Parameters:
  ProjectName:
    Type: String
    Default: fraud-detection-sys
  SrcBucketUrl:
    Description: Bucket location to put s3 buckets
    Default: https://eecs6895-fraud-detection-repo.s3.amazonaws.com
    Type: String
  SrcBucketName:
    Type: String
    Default: eecs6895-fraud-detection-repo
    Description: Bucket that hosts all src files

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # hardcode s3 bucket
      TemplateURL: !Sub ${SrcBucketUrl}/cloudformation/vpc.yaml

  IamRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${SrcBucketUrl}/cloudformation/iam_role.yaml
      Parameters:
        ProjectName: !Ref ProjectName

  ApiLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${SrcBucketUrl}/cloudformation/api_lambda.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        BasicLambdaRoleArn: !GetAtt IamRoleStack.Outputs.LambdaRoleArn
        SecurityGroupId: !GetAtt VpcStack.Outputs.SecurtityGroup1
        PrivateSubnetA: !GetAtt VpcStack.Outputs.PrivateSubnetA
        PrivateSubnetB: !GetAtt VpcStack.Outputs.PrivateSubnetB
        PublicSubnetA: !GetAtt VpcStack.Outputs.PublicSubnetA
        PublicSubnetB: !GetAtt VpcStack.Outputs.PublicSubnetB
#Run this command to update stack
# aws cloudformation update-stack --stack-name test2 --template-body file://cloudformation/root.yaml --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --profile 6895

#Outputs:
#  VPCStackRef:
#    Value: !Ref VpcStack
#  VPCIDRef:
#    Value: !GetAtt
#      - VpcStack
#      - Outputs.VPCID
#  PublicSubnetARef:
#    Value: !GetAtt
#      - VpcStack
#      - Outputs.PublicSubnetA
#  PublicSubnetBRef:
#    Value: !GetAtt
#      - VpcStack
#      - Outputs.PublicSubnetB
#  PrivateSubnetARef:
#    Value: !GetAtt
#      - VpcStack
#      - Outputs.PrivateSubnetA
#  PrivateSubnetBRef:
#    Value: !GetAtt
#      - VpcStack
#      - Outputs.PrivateSubnetB
#  SecurityGroup1IdRef:
#    Value: !GetAtt
#      - VpcStack
#      - Outputs.SecurtityGroup1